//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookHistory
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TaiKhoan_Id { get; set; }
        public Nullable<System.Guid> Xe_Id { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string DiaDiemDen { get; set; }
        public string DiaDiemDi { get; set; }
        public Nullable<double> Sao { get; set; }
        public Nullable<double> KhoangCach { get; set; }
        public string DanhGia { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.Guid> GiamGia_Id { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual DM_Xe DM_Xe { get; set; }
        public virtual DM_MaKhuyenMai DM_MaKhuyenMai { get; set; }
    }
}
