//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Voucher
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> ExpretionDate { get; set; }
        public Nullable<int> Prepayment { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Name { get; set; }
    }
}
